### ISSUE TITLE
kosmos shell imrove code completion

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#133]
e.g. 
<img width="206" alt="image" src="https://user-images.githubusercontent.com/6021844/51438256-450cde00-1caa-11e9-8551-57082938de73.png">

no code completion

**Comment by despiegk** [comment]
works as follows
<img width="784" alt="image" src="https://user-images.githubusercontent.com/6021844/51438266-6b327e00-1caa-11e9-9157-37a718470d9f.png">

**Comment by abom** [comment]
Current way of getting completions doesn't always work, we simply evaluate the line to get an object then get this object's docstring.

The problem is that, not every line (expression or statement) in the shell will evaluate to an object (or JSBase object).

For example, the following won't work (etcd or one won't list any completions)

`cl = j.clients.etcd.one`

In ptpython, jedi doesn't support dynamic attributes, it's used to statically analysis the code and get completions (without executing any code), and because we manipulate `__dict__`, it cannot get this completions right, and as stated [here](https://jedi.readthedocs.io/en/latest/docs/features.html#not-supported) and [here](https://github.com/davidhalter/jedi/issues/997), it's a hard thing to do, and is not supported right now.

I think we need a cleaner way or even type annotations/hinting to help jedi instead (if it would work).

**Comment by abom** [comment]
I added another problem of using eval() in this [commit message](https://github.com/threefoldtech/jumpscaleX/pull/146/commits/4edd3931ea83ac05fb0ae3664a865053d8da10a2), when trying to get the docstring of properties, they get executed (getting parent object wouldn't help too).
