### ISSUE TITLE
Need to another way for asking questions (for encryption) after jsX installation

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/jumpscaleX_archived#163]
need something like environment variables for automating the tests

Questions like:

```Provide a strong secret which will be used to encrypt/decrypt your private key:```

**Comment by abom** [comment]
Setting this into an env variable is not the best solution, IMHO, generating the keys during installation is better.

@rkhamis what do you think?

**Comment by rkhamis** [comment]
Alright, but it needs to check if previously generated. Agreed.

**Comment by abom** [comment]
Added a temporary solutions (not good enough).
Until we decide how to remove the interactive options completely, also what type of encryption we should use, without managing the keys ourselves.

**Comment by despiegk** [comment]
it needs to be interactive, these options cannot be removed.
one of the issues we have is how we do it in the shell that needs to be improved
there is another story/issue about this, when doing autocompletion we need to see how can we get interactivity to work
it worked in ipython, now it gives issues
lets find solution

**Comment by abom** [comment]
In the context of this issue, it doesn't need to exist! and it's a different thing/problem for the shell, because the shell itself is interactive.

But for **automation** like testing or a running server (jumpscale is called an automation framework), for example config files are there for a reason, an automated test or a running server should not stop waiting for user input!

**Comment by despiegk** [comment]
on development_types is done
