### ISSUE TITLE
review nacl

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#174]

**Comment by zaibon** [comment]
So I did some review of the cryptography used in jumpscale, here is my findings:

- JSx uses [pynacl](https://pypi.org/project/PyNaCl/) as a crypto library.
- The nacl module in JSx is responsible for all the crypto

Next is a quick drawing of what and how we store the different keys in jumpscale:
![photo_2019-02-28_11-51-14](https://user-images.githubusercontent.com/303164/53561458-3b02b880-3b4f-11e9-9389-6c4274cc4b55.jpg)

So JSx requires to have one private key. It is used to encrypt any content stored in BCDB and other
- This key is encrypted and saved on the filesystem at `{cfgdir}/nacl/{key_name}.priv`
- The secret/passphrase used to encrypt this key is a secret chosen by the user the first time.
- This secret is also encrypted and stored in redis (I don't know if redis data is persisted on the filesystem or not). This is done so JSx can automatically decrypt the private key when needed
- Finally, the key used to encrypt the secret is a random key generate by jumpscale itself. This makes it the master key of everything. And master key is actually also store in CLEAR TEXT on the filesystem in a "hidden" location `.../var/myprocess_{keyname}.log`

This last point is very important and makes the all security pretty much existent. Cause if you get to the filesystem, you have everything you need to escalate to all the keys present on the system.


Next I'll describe a bit the type of keys that are used.
Currently JSx store an `nacl.public.PrivateKey`, which is a curve25519 key that can be used for encryption.
https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/data/nacl/NACL.py#L155-L161
If we need to sign something, then we generate a `nacl.signing.SigningKey`, which is an ed25519 key, from the raw representation of the private key: https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/data/nacl/NACL.py#L186-L189

I did not find any literature that proof that this practice is actually secure. Which make the current codebase not fitted for do proper signing.
This issue is actually already being tackled in https://github.com/threefoldtech/jumpscaleX/pull/209
The idea is to store the ed25519 key instead of the curve25519, cause We can derive curve25519 from ed25519 and this has been proven to be secure.

**Comment by zaibon** [comment]
Other point worth to mention:
- There is currently no way to recover a private key from mnemonic words (seed) in a non-interactive way. This makes it useless for real programming since in most case you will not have an interactive shell available.
- The API of the nacl module itself is also pretty strange
  - encryptSymmetric method: https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/data/nacl/NACL.py#L186-L189
  It encrypts data using the secret created by the user. So not using the actual KeyPair. Seems this is only used internally in the class. I think this should be move to a private method.
  - decryptSymetric mehtod: https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/data/nacl/NACL.py#L186-L189
   Same remark as encryptSymmetric
  - encrypt: https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/data/nacl/NACL.py#L186-L189
   This method does symetric encryption too but using `nacl.public.SealedBox`. Here is what the documentation says about it:
  > The SealedBox class encrypts messages addressed to a specified key-pair by using ephemeral sender’s keypairs, which will be discarded just after encrypting a single plaintext message.
This kind of construction allows sending messages, which only the recipient can decrypt without providing any kind of cryptographic proof of sender’s authorship. 
  - decrypt method: https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/data/nacl/NACL.py#L186-L189
  This method is the counter party of the encrypt method. But the way the code is written now make it a bit useless. I explain, the encrypt method uses the public key of the jsx user, the decrypt method uses the private key of the jsx user. So this means the only person to who you can send the encrypted message is yourself, since there is no API to encrypt a message using the public key of someone else...
- sign/verify method: https://github.com/threefoldtech/jumpscaleX/blob/682c9be0b68b0c7d56ab21c658bce406aaaed773/Jumpscale/data/nacl/NACL.py#L186-L189
  These 2 methods are ok, you can sign data with your public key, and verify a signature using the public key of someone else.
- Then there are some utility methods like `file_write_hex`, `file_read_hex`, `bin_to_hex`, `hex_to_bin` which IMO doesn't belong there and should be moved into an encoding module or something.

There is currently no API leveraging the `nacl.public.Box`. Here is what the documentation says about it:
> The Box class uses the given public and private (secret) keys to derive a shared key, which is used with the nonce given to encrypt the given messages and to decrypt the given ciphertexts. The same shared key will be generated from both pairing of keys, so given two keypairs belonging to Alice (pkalice, skalice) and Bob (pkbob, skbob), the key derived from (pkalice, skbob) will equal that from (pkbob, skalice).

This type of encryption seems to be the best to use in most case when we want asymmetric encryption. So I think this should be added to the API of the nacl module

**Comment by GlenDC** [comment]
Reviewed. The idea is good, but the implementation can use a lot of improvements. Thank you also @zaibon for reviewing. https://github.com/threefoldtech/home/issues/144 serves as a starting point for the current improvements and open questions (can expand as needed, while still open).

Closing this issue now, as the reviewing is done, the module is understood and reviewed by both @zaibon and @GlenDC which is good enough at this point, and allows us to now bring this module to somewhere we want it to be.

**Comment by GlenDC** [comment]
![img_1904](https://user-images.githubusercontent.com/3900482/54038666-5873fa00-41c1-11e9-94ce-a35182a6b6ec.JPG)

**Comment by despiegk** [comment]
we need to find agreement quickly and then move on.
we don't have time to loose
