### ISSUE TITLE
be able to work from another directory than /sandbox

### ISSUE THREAD

**Issue by zgorizzo69** [threefoldtecharchive/jumpscaleX_archived#474]
The folder /sandbox is hard coded everywhere in the code and dockerfiles
Installation on /sandbox on a local machine forces us to do a sudo and a chown afterwards
It should be nice to be able to git clone JSX in a user define directory than /sandbox
for instance inside a user specific directory instead of a root one.

**Comment by despiegk** [comment]
JSX is not meant to be run on a normal desktop PC its meant to be run for 3bot env's or containers or in development mode but then /sandbox is ok, it does not need to be root e.g. on OSX it works as non root but you need to chown the /sandbox dir so its not really an issue

changing this now has lots of impact because there is quite some magic happening to get it to work for all situation would prefer not to do now
