### ISSUE TITLE
Builders: mongoDb builder

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtecharchive/jumpscaleX_archived#526]
- doesn't follow builders guidlines

**Comment by waleedhammam** [comment]
- branch `development_builder` @ https://github.com/threefoldtech/jumpscaleX/commit/3f32c7a4e52c9f81f72c84af62a7a59d39d2b6b1, https://github.com/threefoldtech/jumpscaleX/commit/ad57d96a867eb40ef088e79db999d97abfbbf70a, https://github.com/threefoldtech/jumpscaleX/commit/dc372ef3d474039033bc7ff536532897e3128445
- Implemented build, install, sandbox, start, stop, test.
- produced flist: https://hub.grid.tf/hammam/mongod.flist.md
* due to new installation you might occur an apt error:
solved by 
`pkill -9 apt-get`
`dpkg --configure -a`

**Comment by Dinaamagdy** [comment]
verified in development_builder branch
