### ISSUE TITLE
cannot use zos client, hangs [development_simple]

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#575]
![image](https://user-images.githubusercontent.com/6021844/58749319-f60b5c80-8484-11e9-8a58-22370a734b16.png)

should be possible to also do ```j.clients.zos.something``` without it to wait
then fill in the properties

there should be more lazy loading I guess

**Comment by zaibon** [comment]
So the actual issue of this bug is in the JSBaseDataObj class, we use `self.name` in the `__str__` method
https://github.com/threefoldtech/jumpscaleX/blob/ce3172c28ab765d2becc3ca7b39c03866eba3646/Jumpscale/core/BASECLASSES/JSBaseDataObj.py#L145-L158

And in the zos client the Node class inherits this `JSBaseDataObj` because of the way config manager works.
But this Node class already defines a `name` property that needs to have a connection to the node to work.
https://github.com/threefoldtech/jumpscaleX/blob/ce3172c28ab765d2becc3ca7b39c03866eba3646/Jumpscale/sal_zos/node/Node.py#L56-L64

So when creating an instance of the client without proper configuration. The object tries to call `__str__` since it is in kosmos shell, which in turn call `name` property that tries to connect to a node that doesn't exists. 

I guess there are multiple way of fixing this. But I also wonder why a base class so low level already reserve a keyword as common as `name`, doesn't feel right.

**Comment by zaibon** [comment]
PR fixing this is ready
