### ISSUE TITLE
python builder not good enough

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#612]
![image](https://user-images.githubusercontent.com/6021844/59390398-6bbed480-8d71-11e9-878c-214079fad392.png)

profile works with python 3.7
rest with 3.6

why can't we use 3.7?
why mixing?

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX/commit/fd9cacd17720d65034b75be433b2f68e7ea61168
default tag is 3.6.8 as the installation comes with it, if you want to change just pass it to build method:
`j.builders.runtimes.python.build(tag="v3.6.8")`

**Comment by Dina-Abd-Elrahman** [comment]
# Note:
it's working fine on `development_builder` , and i got this error in `development` branch. 

#### Branch: `development_builder` , Commit: c9f944ced6a8cfd4110c70d26fcff19a1f632f8c

#### Verification Steps:
-  j.builders.runtimes.python.build(tag="v3.6.8")
- j.builders.runtimes.python.build(tag="v3.7.1") 
- j.builders.runtimes.python.install(reset=True) --> has a bug with installation, it doesn't change the version of python. 

`after i installed python (v3.7.1) , python version in system still 3.6.8`

**Comment by Dina-Abd-Elrahman** [comment]
@waleedhammam  is checking...

**Comment by waleedhammam** [comment]
refactored @ branch: development_builder @ commit: https://github.com/threefoldtech/jumpscaleX/commit/5ef815b2922ce0f29f461270db710582f3aedb28
### Usage:
- set your specific tag you need to build `default 3.6.8` with:
`j.builders.runtimes.python.TAG = "v3.6.8"`
**warning**: some version may not be compatible with capnp schema my corrupt kosmos
if it's already happend just install `"v3.6.8"` with `js_shell`
- build, install, sandbox works as normal
- check installed version with
`which python3`
`python3 --version`
- due to different installation you might occur an apt error:
solved by
`pkill -9 apt-get`
`dpkg --configure -a`

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: development, Commit: 688ba59a635e50ed30551fe7ff37bdeecf84ffbd
